### ISSUE TITLE
Add trvis integration to this repo

### ISSUE THREAD

**Issue by aka-toxa** [andreikramchaninov/guithub#4]
Check assignee to yourself if you want to done this.

**Comment by 4oc3p** [comment]
Note: You can only enable Travis CI builds for repositories you have admin access to.

**Comment by aka-toxa** [comment]
anyone who assigned tasks to him self can ask @andreikramchaninov to get an admin access

**Comment by 4oc3p** [comment]
Check please https://github.com/andreikramchaninov/guithub/pull/12 pull request.
If it will pass, we can merge.
